[workspace]
authors = ["wsy94 <wsy94@temple.edu>"]
channels = ["conda-forge"]
name = "SciView"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
launch-app = { cmd = "python -m sciview.launchers app", env = { PYTHONPATH = "src" } }

[dependencies]
python = "3.12.*"
pytest = ">=9.0.3,<10"
pyyaml = ">=6.0.3,<7"
pillow = ">=12.2.0,<13"
numpy = ">=2.4.3,<3"
pyqt = ">=5.15.11,<6"
matplotlib = ">=3.10.9,<4"
scipy = ">=1.17.1,<2"
scitoolsscianalysis = ">=2.6.6,<3"
psutil = ">=7.1.0,<8"
tiled = ">=0.1"
ipython = ">=9.13.0,<10"
ipdb = ">=0.13.13,<0.14"
debugpy = ">=1.8.20,<2"
bluesky-tiled-plugins = ">=0.2.0"
