"""Dedicated Info tab that centralizes image information display."""

from PyQt5.QtWidgets import QVBoxLayout

from tabs.base_image_tab import BaseImageTab


class InfoTab(BaseImageTab):
    """Centralized image information tab."""

    def __init__(self, parent_app):
        super().__init__(parent_app)
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(2, 2, 2, 2)
        layout.addWidget(self._create_image_info_panel())

    def set_shared_info_text(self, info_text):
        """Set shared image information generated by another tab."""
        self._set_image_info_text(info_text)

    def update_plot(self, image_data=None):
        """Info tab has no plot canvas; ignore shared plot refresh calls."""
        return
